baseURL = "https://blog.kuytu.com/"
languageCode = "en-us"
title = "Turgut Şimşek"
theme = "PaperMod"

# Search için gerekli
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowSearch = true

  [params.profileMode]
    enabled = true
    title = "Turgut Şimşek"
    imageUrl = "/pic/me.jpg"
    imageTitle = "Turgut Şimşek"
    imageWidth = 120
    imageHeight = 120
    [[params.profileMode.buttons]]
      name = "Blog Yazıları"
      url = "/posts"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/geveZEUS/"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/turgutsimsek/"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/gevezeus/"
  [[params.socialIcons]]
    name = "lastfm"
    url = "https://www.last.fm/user/gevezeus"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Ana Sayfa"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 15
  [[menu.main]]
    identifier = "tags"
    name = "Etiketler"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Arama"
    url = "/search/"
    weight = 30
